apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-gateway-premium-ro-system

commonLabels:
  node.statcan.gc.ca/purpose: system

resources:
  - ../kustomize-gateway/overlays/gateway-ro/
